const fs = require("fs");
const path = require("path");

const root = __dirname;
const entry = "src/bootstrap.js";
const output = path.join(root, "main.js");
const externals = new Set(["obsidian"]);
const modules = new Map();

function normalizeModulePath(modulePath) {
  return modulePath.replace(/\\/g, "/");
}

function resolveModule(fromId, request) {
  if (request.startsWith("src/")) return { external: false, id: request };
  if (!request.startsWith(".")) return { external: true, id: request };
  const base = path.dirname(fromId);
  let resolved = normalizeModulePath(path.join(base, request));
  if (!resolved.endsWith(".js")) resolved += ".js";
  return { external: false, id: resolved };
}

function collect(id) {
  if (modules.has(id)) return;
  const absolute = path.join(root, id);
  const code = fs.readFileSync(absolute, "utf8");
  modules.set(id, code);
  const requireRegex = /require\(["']([^"']+)["']\)/g;
  let match;
  while ((match = requireRegex.exec(code))) {
    const resolved = resolveModule(id, match[1]);
    if (!resolved.external && !externals.has(resolved.id)) collect(resolved.id);
  }
}

collect(entry);

let bundle = "// Generated by build.js. Edit src/ files, not this bundle.\n";
bundle += "(function() {\n";
bundle += "const __externalRequire = require;\n";
bundle += "const __modules = {\n";
for (const [id, code] of modules.entries()) {
  bundle += JSON.stringify(id) + ": function(module, exports, __require, __externalRequire) {\n";
  bundle += "const require = (request) => __require(request, " + JSON.stringify(id) + ");\n";
  bundle += code.trimEnd() + "\n";
  bundle += "},\n";
}
bundle += "};\n";
bundle += "const __cache = {};\n";
bundle += "function __require(id, fromId) {\n";
bundle += "  if (!id.startsWith('.') && !id.startsWith('src/')) return __externalRequire(id);\n";
bundle += "  if (id.startsWith('src/')) {\n";
bundle += "    if (!id.endsWith('.js')) id += '.js';\n";
bundle += "    if (__cache[id]) return __cache[id].exports;\n";
bundle += "    const factory = __modules[id];\n";
bundle += "    if (!factory) throw new Error('Module not found: ' + id);\n";
bundle += "    const module = { exports: {} };\n";
bundle += "    __cache[id] = module;\n";
bundle += "    factory(module, module.exports, (request) => __require(request, id), __externalRequire);\n";
bundle += "    return module.exports;\n";
bundle += "  }\n";
bundle += "  const base = fromId ? fromId.slice(0, fromId.lastIndexOf('/') + 1) : '';\n";
bundle += "  let resolved = (base + id).replace(/\\\\/g, '/');\n";
bundle += "  const parts = [];\n";
bundle += "  for (const part of resolved.split('/')) {\n";
bundle += "    if (!part || part === '.') continue;\n";
bundle += "    if (part === '..') parts.pop(); else parts.push(part);\n";
bundle += "  }\n";
bundle += "  resolved = parts.join('/');\n";
bundle += "  if (!resolved.endsWith('.js')) resolved += '.js';\n";
bundle += "  if (__cache[resolved]) return __cache[resolved].exports;\n";
bundle += "  const factory = __modules[resolved];\n";
bundle += "  if (!factory) throw new Error('Module not found: ' + resolved + ' from ' + fromId);\n";
bundle += "  const module = { exports: {} };\n";
bundle += "  __cache[resolved] = module;\n";
bundle += "  factory(module, module.exports, (request) => __require(request, resolved), __externalRequire);\n";
bundle += "  return module.exports;\n";
bundle += "}\n";
bundle += "const pluginModule = __require('./" + entry + "', '');\n";
bundle += "module.exports = pluginModule.default || pluginModule;\n";
bundle += "})();\n";

fs.writeFileSync(output, bundle, "utf8");
